DELETE FROM reservation;
DELETE FROM hoteluser;
DELETE FROM room;

-- TODO: Need to set some default pre-configured reservations
-- insert into reservation
--     (id,
--      dailyRate,
--      endDate,
--      isConfirmed,
--      isNotStarted,
--      isPromoApplied,
--      numDays,
--      startDate,
--      totalRate,
--      guest_id,
--      room_id)
-- values ();
-- TODO: Need to set default user
-- insert into hoteluser
--     (id,
--      city,
--      email,
--      firstName,
--      lastName,
--      password,
--      phoneNumber,
--      role,
--      state,
--      streetAddress,
--      username,
--      zipCode)
-- values ();
-- TODO: Need to set default room
-- insert into room
--     (id,
--      baseRate,
--      bedNumber,
--      bedType,
--      quality,
--      roomNumber,
--      smokingStatus)
-- values ();
